apiVersion: policy.giantswarm.io/v1alpha1
kind: PolicyException
metadata:
  name: {{ .Values.node.name }}
  namespace: policy-exceptions
{{ include "nfs.labels" . | indent 2 }}
spec:
  policies:
    - disallow-capabilities
    - disallow-capabilities-strict
    - disallow-host-namespaces
    - disallow-host-path
    - disallow-privilege-escalation
    - disallow-privileged-containers
    - require-run-as-nonroot
    - restrict-volume-types
  targets:
    - kind: DaemonSet
      namespaces:
      - {{ .Release.Namespace }}
      names:
      - {{ .Values.node.name }}*
---
apiVersion: policy.giantswarm.io/v1alpha1
kind: PolicyException
metadata:
  name: {{ .Values.controller.name }}
  namespace: policy-exceptions
{{ include "nfs.labels" . | indent 2 }}
spec:
  policies:
    - disallow-capabilities
    - disallow-capabilities-strict
    - disallow-host-namespaces
    - disallow-host-path
    - disallow-privilege-escalation
    - disallow-privileged-containers
    - require-run-as-nonroot
    - restrict-volume-types
  targets:
    - kind: Deployment
      namespaces:
      - {{ .Release.Namespace }}
      names:
      - {{ .Values.controller.name }}*
