apiVersion: policy.giantswarm.io/v1alpha1
kind: PolicyException
metadata:
  name: {{ .Values.node.name }}
  namespace: {{ .Release.Namespace }}
{{ include "nfs.labels" . | indent 2 }}
spec:
  policies:
    - disallow-capabilities
    - disallow-host-namespaces
    - disallow-privileged-containers
  targets:
    - kind: DaemonSet
      namespaces:
      - {{ .Release.Namespace }}
      names:
      - {{ .Values.node.name }}*
---
apiVersion: policy.giantswarm.io/v1alpha1
kind: PolicyException
metadata:
  name: {{ .Values.controller.name }}
  namespace: {{ .Release.Namespace }}
{{ include "nfs.labels" . | indent 2 }}
spec:
  policies:
    - disallow-capabilities
    - disallow-host-namespaces
    - disallow-privileged-containers
  targets:
    - kind: Deployment
      namespaces:
      - {{ .Release.Namespace }}
      names:
      - {{ .Values.controller.name }}*
